# Generated by Django 4.2.3 on 2024-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用餐记录ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="日期")),
                ("dish_name", models.CharField(max_length=200, verbose_name="餐品名称")),
                ("price", models.FloatField(default=0, verbose_name="价格")),
            ],
            options={
                "verbose_name": "用餐记录",
                "verbose_name_plural": "用餐记录",
                "db_table": "record",
                "ordering": ["-date"],
            },
        ),
    ]
