# Generated by Django 4.2.3 on 2024-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0003_alter_record_options_rename_date_record_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="time",
            field=models.CharField(blank=True, max_length=200, verbose_name="日期"),
        ),
    ]
