# Generated by Django 4.2.3 on 2024-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0005_remove_record_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="dish_name",
            field=models.CharField(
                default="反正吃了什么", max_length=200, verbose_name="餐品名称"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="time",
            field=models.CharField(blank=True, max_length=200, verbose_name="日期"),
        ),
    ]
