# Generated by Django 5.0.7 on 2024-07-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (1, "学一"),
                            (2, "学二"),
                            (3, "学三"),
                            (4, "学四"),
                            (5, "学五"),
                            (6, "学六"),
                            (20, "美食苑"),
                            (114514, "其他"),
                        ],
                        default=0,
                        verbose_name="用餐地点",
                    ),
                ),
                ("description", models.CharField(default="这里可以吃饭", max_length=500)),
                (
                    "address",
                    models.CharField(
                        blank=True, default="吃饭就在这里", max_length=200, null=True
                    ),
                ),
                ("image", models.CharField(default="", max_length=500)),
                (
                    "dishes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_dishes",
                        to="dish.dish",
                    ),
                ),
            ],
            options={
                "verbose_name": "餐厅",
                "verbose_name_plural": "餐厅s",
                "db_table": "restaurant",
            },
        ),
    ]
