# Generated by Django 4.2.3 on 2023-12-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creater',
            new_name='creator',
        ),
    ]
