# Generated by Django 4.2.3 on 2024-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0006_alter_dish_description"),
        ("restaurant", "0002_alter_restaurant_dishes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="dishes",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="dishes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="restaurant_dishes",
                to="dish.dish",
            ),
        ),
    ]
