# Generated by Django 4.2.3 on 2023-12-22 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='agree',
        ),
        migrations.AddField(
            model_name='post',
            name='agrees',
            field=models.ManyToManyField(related_name='agreedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
