# Generated by Django 4.2.3 on 2023-12-22 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0007_remove_post_agree_post_agrees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='agree',
        ),
        migrations.AddField(
            model_name='comment',
            name='agrees',
            field=models.ManyToManyField(related_name='agreedComments', to=settings.AUTH_USER_MODEL),
        ),
    ]
