# Generated by Django 4.2.3 on 2023-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_options_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avg_price',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
