# Generated by Django 4.2.3 on 2023-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_post_avg_price_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avg_price',
            field=models.IntegerField(default=0),
        ),
    ]
