# Generated by Django 4.2.3 on 2024-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0004_alter_comment_options_remove_comment_dish_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="comments",
        ),
        migrations.AddField(
            model_name="user",
            name="comments",
            field=models.ManyToManyField(
                related_name="user_comments", to="comment.comment"
            ),
        ),
    ]
