# Generated by Django 4.2.3 on 2023-12-19 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='fans',
            new_name='subscriber',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribes',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribes',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', through='users.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
