# Generated by Django 4.2.3 on 2024-07-28 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_comments_user_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login_at", models.DateTimeField()),
                ("expires_by", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
