# Generated by Django 4.2.3 on 2023-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_fans_subscribe_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
