# Generated by Django 4.2.3 on 2024-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_authrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="默认用户名",
                error_messages={"unique": "该邮箱已被注册"},
                max_length=200,
                unique=True,
                verbose_name="用户名",
            ),
        ),
    ]
