# Generated by Django 4.2.3 on 2024-07-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="默认用户名", max_length=200, verbose_name="用户名"),
        ),
    ]
