# Generated by Django 4.2.3 on 2024-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="motto",
            field=models.CharField(
                default="这个人很懒，什么都没有留下", max_length=256, verbose_name="个性签名"
            ),
        ),
    ]
