# Generated by Django 4.2.3 on 2024-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0006_alter_comment_id"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_user_motto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="user_comments", to="comment.comment"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                related_query_name="custom_user",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                related_query_name="custom_user",
                to="auth.permission",
            ),
        ),
    ]
