# Generated by Django 4.2.3 on 2024-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_comments_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthRecord",
        ),
    ]
