# Generated by Django 4.2.3 on 2024-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_delete_authrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True, default="计算机学院", max_length=200, verbose_name="学院"
            ),
        ),
    ]
