# Generated by Django 4.2.3 on 2024-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="word",
            field=models.CharField(blank=True, max_length=256, verbose_name="码"),
        ),
    ]
