# Generated by Django 4.2.3 on 2024-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_restaurant_dishes_restaurant_dishes"),
        ("comment", "0006_alter_comment_id"),
        ("dish", "0007_alter_dish_comments"),
        ("users", "0013_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="collected_comments",
            field=models.ManyToManyField(
                blank=True, related_name="collected_user", to="comment.comment"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="collected_dishes",
            field=models.ManyToManyField(
                blank=True, related_name="collected_user", to="dish.dish"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="collected_restaurants",
            field=models.ManyToManyField(
                blank=True, related_name="collected_user", to="restaurant.restaurant"
            ),
        ),
    ]
