# Generated by Django 4.2.3 on 2024-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
        ("users", "0014_user_collected_comments_user_collected_dishes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="records",
            field=models.ManyToManyField(
                blank=True, related_name="user_records", to="record.record"
            ),
        ),
    ]
