# Generated by Django 5.0.7 on 2024-07-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.CharField(
                        default="https://pigkiller-011955-1319328397.cos.ap-beijing.myqcloud.com/img/202407241935479.jpg",
                        max_length=500,
                        verbose_name="图片",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("description", models.TextField(max_length=500)),
                ("overall_rating", models.FloatField()),
                ("flavor_rating", models.FloatField()),
                ("waiting_time", models.FloatField()),
                ("restaurant_name", models.CharField(max_length=200)),
                (
                    "comments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_comments",
                        to="comment.comment",
                    ),
                ),
            ],
            options={
                "db_table": "dish",
                "ordering": ["-name"],
            },
        ),
    ]
