# Generated by Django 4.2.3 on 2024-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0006_alter_comment_id"),
        ("dish", "0003_alter_dish_options_remove_dish_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="restaurant_name",
            field=models.CharField(default="默认地址", max_length=500, verbose_name="菜品餐厅"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="dish_comments",
                to="comment.comment",
                verbose_name="评论",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(default=0, max_length=500, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="flavor_rating",
            field=models.FloatField(default=0, verbose_name="风味评分"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="id",
            field=models.AutoField(
                auto_created=True,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="评论ID",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(default="菜品名称", max_length=100, verbose_name="菜品名称"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="overall_rating",
            field=models.FloatField(default=0, verbose_name="总体评分"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.FloatField(default=0, verbose_name="价格"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="waiting_time",
            field=models.FloatField(default=0, verbose_name="等待时间"),
        ),
    ]
