# Generated by Django 4.2.3 on 2024-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0004_dish_restaurant_name_alter_dish_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="address",
            field=models.CharField(default="默认地址", max_length=100, verbose_name="餐厅地址"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(
                default="暂时还没有描述", max_length=500, verbose_name="描述"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="restaurant_name",
            field=models.CharField(default="默认餐厅", max_length=500, verbose_name="菜品餐厅"),
        ),
    ]
