# Generated by Django 4.2.3 on 2024-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0005_alter_dish_address_alter_dish_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(
                default="暂时还没有描述。/", max_length=500, verbose_name="描述"
            ),
        ),
    ]
