# Generated by Django 4.2.3 on 2024-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0006_alter_comment_id"),
        ("dish", "0006_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="dish_comments",
                to="comment.comment",
                verbose_name="评论",
            ),
        ),
    ]
