# Generated by Django 4.2.3 on 2024-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0007_alter_dish_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="id",
            field=models.AutoField(
                auto_created=True,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="菜品ID",
            ),
        ),
    ]
