# Generated by Django 5.0.7 on 2024-07-26 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_comment_restaurant"),
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dish_name",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="restaurant_name",
        ),
        migrations.AddField(
            model_name="comment",
            name="dish",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="dish.dish"
            ),
        ),
    ]
