# Generated by Django 4.2.3 on 2024-07-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0004_alter_comment_options_remove_comment_dish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dish_name",
            field=models.CharField(default="菜品", max_length=200, verbose_name="对应菜品"),
        ),
        migrations.AddField(
            model_name="comment",
            name="restaurant_name",
            field=models.CharField(default="默认食堂", max_length=200, verbose_name="所属食堂"),
        ),
    ]
